// AUTO-GENERATED by abi_layout_asserts.py -- do not edit by hand.
// Regenerate after any intentional struct change and commit the result.
#pragma once

#include <assert.h>    // static_assert (C11)
#include <stddef.h>    // offsetof
#include <stdalign.h>  // alignof (C11)


