// AUTO-GENERATED by abi_layout_asserts.py -- do not edit by hand.
// Regenerate after any intentional struct change and commit the result.
#pragma once

#include <assert.h>    // static_assert (C11)
#include <stddef.h>    // offsetof
#include <stdalign.h>  // alignof (C11)

#include <liara/modules.h>
#include <liara/renderer/packet.h>

static_assert(sizeof(liara_module_info_t) == 1u, "ABI: sizeof(liara_module_info_t) changed");
static_assert(alignof(liara_module_info_t) == 1u, "ABI: alignof(liara_module_info_t) changed");
static_assert(offsetof(liara_module_info_t, struct_version) == -1u, "ABI: offsetof(liara_module_info_t.struct_version) changed");
static_assert(offsetof(liara_module_info_t, abi_version) == -1u, "ABI: offsetof(liara_module_info_t.abi_version) changed");
static_assert(offsetof(liara_module_info_t, module_version) == -1u, "ABI: offsetof(liara_module_info_t.module_version) changed");
static_assert(offsetof(liara_module_info_t, reserved) == -1u, "ABI: offsetof(liara_module_info_t.reserved) changed");
static_assert(offsetof(liara_module_info_t, module_name) == -1u, "ABI: offsetof(liara_module_info_t.module_name) changed");
static_assert(offsetof(liara_module_info_t, abi_version_str) == -1u, "ABI: offsetof(liara_module_info_t.abi_version_str) changed");
static_assert(offsetof(liara_module_info_t, module_version_str) == -1u, "ABI: offsetof(liara_module_info_t.module_version_str) changed");

static_assert(sizeof(liara_render_drawable_t) == 12u, "ABI: sizeof(liara_render_drawable_t) changed");
static_assert(alignof(liara_render_drawable_t) == 4u, "ABI: alignof(liara_render_drawable_t) changed");
static_assert(offsetof(liara_render_drawable_t, x) == 0u, "ABI: offsetof(liara_render_drawable_t.x) changed");
static_assert(offsetof(liara_render_drawable_t, y) == 4u, "ABI: offsetof(liara_render_drawable_t.y) changed");
static_assert(offsetof(liara_render_drawable_t, color) == 8u, "ABI: offsetof(liara_render_drawable_t.color) changed");

static_assert(sizeof(liara_render_packet_t) == 32u, "ABI: sizeof(liara_render_packet_t) changed");
static_assert(alignof(liara_render_packet_t) == 8u, "ABI: alignof(liara_render_packet_t) changed");
static_assert(offsetof(liara_render_packet_t, struct_version) == 0u, "ABI: offsetof(liara_render_packet_t.struct_version) changed");
static_assert(offsetof(liara_render_packet_t, grid_width) == 4u, "ABI: offsetof(liara_render_packet_t.grid_width) changed");
static_assert(offsetof(liara_render_packet_t, grid_height) == 6u, "ABI: offsetof(liara_render_packet_t.grid_height) changed");
static_assert(offsetof(liara_render_packet_t, background_color) == 8u, "ABI: offsetof(liara_render_packet_t.background_color) changed");
static_assert(offsetof(liara_render_packet_t, drawables) == 16u, "ABI: offsetof(liara_render_packet_t.drawables) changed");
static_assert(offsetof(liara_render_packet_t, drawable_count) == 24u, "ABI: offsetof(liara_render_packet_t.drawable_count) changed");

